---
driver:
  name: hyperv
  memory_startup_bytes: 1073741824
  password: 'P@ssw0rd!'

transport:
  name: winrm

verifier:
  name: pester

provisioner:
  name: dsc
  driver:
    parent_vhd: 'C:\Hyper-V\BaseImages\Windows2012R2-Base.vhd'

platforms:
  - name: windows_2012r2

suites:
  - name: cWebsite_StopWebsite
  - name: cWebsite_StartWebsite