---
driver:
  provider: hyperv
  name: vagrant
  vm_hostname: false # do not bother trying to change the hostname (sometimes fails)
  communicator: winrm

transport:
  name: winrm

verifier:
  name: pester

provisioner:
  name: dsc

platforms:
  - name: windows_2012r2
    driver:
      box: ws2012r2

suites:
  - name: cWebsite_StopWebsite
  - name: cWebsite_StartWebsite