---
driver:
  name: vagrant
  vm_hostname: false # do not bother trying to change the hostname (sometimes fails)
  communicator: winrm
  linked_clones: true
  gui: false
  customize:
    cpus: 2
    memory: 2048

platforms:
  - name: windows_2012r2_wmf4
    driver:
      box: smurawski/2012R2-wmf4
  - name: windows_2012r2_wmf5
    driver:
      box: smurawski/2012R2-wmf5
