---
driver:
  name: hyperv
  memory_startup_bytes: 1073741824
  password: 'P@ssw0rd!'

platforms:
  - name: windows_2012r2
    driver:
      parent_vhd: 'C:\Hyper-V\BaseImages\Windows2012R2-Base.vhd'
