---
driver:
  name: vagrant
  provider: vmware_fusion
  guest: :windows
  vm_hostname: false
  synced_folders:
    - ["./local_cache", "/vagrant"]

provisioner:
  name: dsc  
  chef_installer_path: 'c:/vagrant/chef-windows-11.16.4-1.windows.msi'

platforms:
  - name: wmf5
    transport: 
      name: winrm 
      max_threads: 1 
    driver:
      box: ws2012r2_wmf5

suites:
  - name: cWebsite_StopWebsite
  - name: cWebsite_StartWebsite